name       : fuse-zip
version    : 0.7.0
release    : 1
source     :
    - https://bitbucket.org/agalanin/fuse-zip/downloads/fuse-zip-0.7.0.tar.gz : 47306bab2b8b0db8ca6fac01833ccfb4394ddae1943ab2e7020b1bdbb210410b
license    : GPL-3.0-or-later
component  : system.utils
summary    : FUSE filesystem to mount ZIP archives with write support
description: |
    FUSE filesystem to mount ZIP archives with write support
builddeps  :
  - pkgconfig(fuse)
  - pkgconfig(libzip)
install    : |
    %make_install prefix=/usr
    rm -rf $installdir/usr/share/doc
